---
- hosts: master1
  tasks:
  - name: Generate cert masters
    shell: kubeadm init phase upload-certs --upload-certs | tail -1
    register: cert_masters

  - name: Set fact for cert masters
    set_fact:
      cert_masters_command: "{{ cert_masters.stdout_lines[0] }}"

  - name: Display cert_masters output
    debug:
      var: hostvars['master1'].cert_masters_command

  - name: Generate join command
    shell: kubeadm token create --print-join-command
    register: join_command


  - name: Set fact for join command
    set_fact:
      kube_join_command: "{{ join_command.stdout }}"
  - name: Display join command output
    debug:
      var: hostvars['master1'].kube_join_command