apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ STORAGE_CLASS_NAME }}
provisioner: nfs.csi.k8s.io
parameters:
  server: {{ NFS_IP }}
  share: {{ SHARE_PATH }}
reclaimPolicy: {{ POLICY }}
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=3