---
- hosts: [workers]

  tasks:

  - name: Check if Kubelet is running
    shell: netstat -tulpn | grep kubelet
    register: kubelet_status
    ignore_errors: true

  - name: Print kubestat
    debug:
      var: kubestatus.stdout

  - name: Join the extra masters to cluster
    shell: "{{ hostvars['master1'].kube_join_command }} "
    when: kubelet_status.stdout == ""