---
#- include: 'k8s/1_setup_k8s_requirements.yaml'

# install and configure keepalived
#- include: 'keepalived/1_install_keepalived.yaml'

# install haproxy
#- include: 'haproxy/1_install_haproxy.yaml'

# init first master node
#- include: 'k8s/2_init_first_master.yaml'

# generate cert and string for connetcion
- include: 'k8s/3_generate_cert_and_init.yaml'
# add other controls
- include: 'k8s/4_init_other_masters.yaml'

# add CNI
- include: 'k8s/5_init_network_provider.yaml'