---
- hosts: all
  vars_files:
    - ../../variables.yaml
  tasks:

  - name: Install dependencies
    apt:
      name:
        - gnupg2
        - apt-transport-https
        - ca-certificates
      state: present

  - name: Add repository pubkey for GlusterFS
    apt_key:
      url: "{{ GLUSTERFS_APT_KEY }}"
      state: present
      keyring: "{{ GLUSTERFS_KEY_PATH }}"

  - name: Add debian repo for GlusterFS
    apt_repository:
      repo: "{{ GLUSTERFS_REPO }}"
      state: present
      filename: gluster

  - name: Install glusterfs
    apt:
      name:
        - glusterfs-server
        - glusterfs-client
      state: present

  - name: Start/Enable glusterd
    service:
      name: glusterd
      state: started
      enabled: yes
